spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/sequence_test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

